name: ShulkerBoxProtect
version: '1.0'
main: yusama125718.shulkerboxprotect.ShulkerBoxProtect
api-version: 1.19

commands:
  shulkerp:
    description: ShulkerBoxProtect
    usage: /shulkerpでコマンドを確認

permissions:
  shulkerp.op:
    default: op